name: Links
permissions:
  contents: read
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    uses: bl4ko/shared-actions/.github/workflows/links.yml@17c978073fd13fbd0bd5e8cfe16410f5bf8c746d # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
