name: Links
permissions:
  contents: read
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    uses: bl4ko/shared-actions/.github/workflows/links.yml@a81bad9b67ca47f214e721365c81b5bf06c7b340 # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
