name: Links
permissions:
  contents: read
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    uses: bl4ko/shared-actions/.github/workflows/links.yml@831196c62c8fca79a978a088f9ac140fc8da336d # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
