name: Create Release 🚀
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    uses: bl4ko/shared-actions/.github/workflows/release.yml@b113c8541070e4e35017d31174f6e765b1da0b5d # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
