name: Create Release 🚀
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    uses: bl4ko/shared-actions/.github/workflows/release.yml@94ac0797da8ab5f0a93c8ad8c4ce9601901fae7d # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
