name: Check for vulnerabilities

on:
  pull_request:
    branches:
      - main

jobs:
  vulnerabilities:
    name: Check for vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45
        with:
          files: |
            cmd/**
            internal/**
            .golangci.yml
            go.mod
            go.sum
            .dockerignore
            Dockerfile

      # https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#scan-ci-pipeline
      - name: Build an image from Dockerfile
        if: steps.changed-files.outputs.any_modified == 'true'
        run: |
          docker build -t netbox-ssot:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: aquasecurity/trivy-action@master
        # We use proxies to avoid rate limiting for trivy database
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db
        with:
          image-ref: netbox-ssot:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
